[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "asyncio>=4.0.0",
    "discord-py>=2.6.3",
    "pycharacterai>=2.2.50",
    "python-dotenv>=1.1.1",
]
